<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Unsga3Bend.Ab</RootNamespace>
    <AssemblyName>csharp_core_dump</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="$(Unsga3Project)" Condition="'$(Unsga3Project)' != ''" />
  </ItemGroup>
</Project>
