#!/usr/bin/env python3
"""Optional C# catalog Run dump.

C# ``tools/OracleCompare`` accepts only zdt1, zdt2, and dtlz2. This
script runs the unconstrained catalog through the Unsga3 library when
``UNSGA3_CS_ROOT`` points at a checkout **outside** this repo. It does
not clone Unsga3 and it does not call OracleCompare.

Knobs come from the caller (``ab/oracle_catalog.py`` passes
``catalog_knobs``). Tournament is ``PymooCompatible`` (``--pymoo-mode``
shape: ``TournamentMode.PymooCompatible``). The written rows are the
feasible non-dominated front, same definition as OracleCompare.

Missing root / dotnet / a build failure prints ``skip:`` and exits 0.
No invented fronts. OSY / TNK / C1-DTLZ1 are not run.
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

from protocol import CATALOG_PROBLEMS, catalog_knobs

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "ab" / "out"
RUNNER = OUT_DIR / "csharp_catalog_runner"

PROGRAM = r"""using System.Globalization;
using Unsga3.Algorithm;
using Unsga3.Core;
using Unsga3.Operators.Selection;
using Unsga3.Problems;
using Unsga3.Utilities;

// Generated by ab/dump_csharp_catalog.py. Not OracleCompare.
// Front = feasible non-dominated solutions (OracleCompare definition).

if (args.Length < 6)
{
    Console.Error.WriteLine("usage: CatalogDump problem partitions pop gens seed out.csv");
    return 2;
}

string problemName = args[0];
int partitions = int.Parse(args[1], CultureInfo.InvariantCulture);
int pop = int.Parse(args[2], CultureInfo.InvariantCulture);
int gens = int.Parse(args[3], CultureInfo.InvariantCulture);
int seed = int.Parse(args[4], CultureInfo.InvariantCulture);
string outPath = args[5];

IProblem problem = problemName.ToLowerInvariant() switch
{
    "zdt3" => new Zdt3Problem(),
    "zdt4" => new Zdt4Problem(),
    "zdt6" => new Zdt6Problem(),
    "dtlz1" => new Dtlz1Problem(nObjectives: 3, k: 5),
    "dtlz3" => new Dtlz3Problem(nObjectives: 3, k: 10),
    "dtlz4" => new Dtlz4Problem(nObjectives: 3, k: 10),
    "dtlz7" => new Dtlz7Problem(nObjectives: 3, k: 20),
    "sphere" => new SphereProblem(nVariables: 10),
    "ackley" => new AckleyProblem(nVariables: 30),
    "rosenbrock" => new RosenbrockProblem(nVariables: 10),
    _ => null!,
};

if (problem is null)
{
    Console.Error.WriteLine($"Unknown catalog problem: {problemName}");
    return 2;
}

int m = problem.NumberOfObjectives;
var dirs = ReferenceDirections.DasDennis(m, partitions);
var algo = new Unsga3Algorithm(
    dirs,
    populationSize: pop,
    seed: seed,
    tournamentMode: TournamentMode.PymooCompatible);
var result = algo.Run(problem, gens);

var obtained = result.NonDominatedSolutions
    .Where(i => i.IsFeasible)
    .Select(i => (double[])i.Objectives.Clone())
    .ToArray();
if (obtained.Length == 0)
    obtained = result.FinalPopulation.Select(i => (double[])i.Objectives.Clone()).ToArray();

var dest = new FileInfo(outPath);
dest.Directory?.Create();
using (var sw = new StreamWriter(dest.FullName))
{
    sw.WriteLine(
        $"# run: {problemName} n_obj={m} n_var={problem.NumberOfVariables} partitions={partitions} pop={pop} gens={gens} seed={seed} tournament=PymooCompatible source=csharp-catalog");
    foreach (var row in obtained)
        sw.WriteLine(string.Join(",", row.Select(v => v.ToString("G17", CultureInfo.InvariantCulture))));
}

Console.Error.WriteLine($"wrote {dest.FullName} ({obtained.Length} front rows)");
return 0;
"""

CSPROJ = """<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>CatalogDump</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="{csproj}" />
  </ItemGroup>
</Project>
"""


def skip(msg: str) -> int:
    print(f"skip: {msg}", file=sys.stderr)
    return 0


def tool_env() -> dict[str, str]:
    env = os.environ.copy()
    home = Path.home()
    extras = [str(home / ".dotnet"), str(home / ".local" / "bin")]
    path = env.get("PATH", "")
    for extra in extras:
        if extra not in path.split(":"):
            path = extra + ":" + path
    env["PATH"] = path
    env.setdefault("DOTNET_ROOT", str(home / ".dotnet"))
    env.setdefault("DOTNET_CLI_TELEMETRY_OPTOUT", "1")
    env.setdefault("DOTNET_NOLOGO", "1")
    return env


def ensure_runner(cs_root: Path, env: dict[str, str]) -> Path | str:
    lib = cs_root / "src" / "Unsga3" / "Unsga3.csproj"
    if not lib.is_file():
        return f"UNSGA3_CS_ROOT={cs_root} has no src/Unsga3/Unsga3.csproj"
    dotnet = shutil.which("dotnet", path=env.get("PATH"))
    if not dotnet:
        return "dotnet is not on PATH; cannot run the C# catalog dump"
    RUNNER.mkdir(parents=True, exist_ok=True)
    (RUNNER / "Program.cs").write_text(PROGRAM, encoding="utf-8")
    (RUNNER / "CatalogDump.csproj").write_text(
        CSPROJ.format(csproj=lib.resolve().as_posix()),
        encoding="utf-8",
    )
    dll = RUNNER / "bin" / "Release" / "net10.0" / "CatalogDump.dll"
    # Rebuild when the generated source is newer than the dll.
    if dll.is_file() and dll.stat().st_mtime >= (RUNNER / "Program.cs").stat().st_mtime:
        return dll
    proc = subprocess.run(
        [dotnet, "build", str(RUNNER / "CatalogDump.csproj"), "-c", "Release", "-v", "q"],
        check=False,
        capture_output=True,
        text=True,
        env=env,
    )
    if proc.returncode != 0 or not dll.is_file():
        detail = (proc.stderr or proc.stdout or "dotnet build failed").strip()
        if len(detail) > 800:
            detail = detail[:800] + "…"
        return f"C# catalog runner build failed: {detail}"
    return dll


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--problem", choices=CATALOG_PROBLEMS, required=True)
    parser.add_argument("--partitions", type=int, default=None)
    parser.add_argument("--pop", type=int, default=None)
    parser.add_argument("--gens", type=int, default=None)
    parser.add_argument("--seed", type=int, default=1)
    parser.add_argument(
        "--tournament",
        choices=("pymoo",),
        default="pymoo",
        help="catalog A/B stays PymooCompatible (accepted so the shared dumper can pass the flag)",
    )
    parser.add_argument("--out", type=Path, default=OUT_DIR / "csharp_catalog_F.csv")
    args = parser.parse_args()

    cs_root = os.environ.get("UNSGA3_CS_ROOT", "").strip()
    if not cs_root:
        return skip(
            "C# catalog dump is optional. Set UNSGA3_CS_ROOT to a local "
            "checkout of https://github.com/AppSprout-dev/Unsga3 outside this "
            "repo. OracleCompare does not accept catalog problem names. "
            "This tree does not clone Unsga3."
        )

    env = tool_env()
    built = ensure_runner(Path(cs_root).expanduser().resolve(), env)
    if isinstance(built, str):
        return skip(built + ". Refusing to invent a front.")

    knobs = catalog_knobs(args.problem)
    partitions = args.partitions if args.partitions is not None else int(knobs["partitions"])
    pop = args.pop if args.pop is not None else int(knobs["pop"])
    gens = args.gens if args.gens is not None else int(knobs["gens"])
    args.out.parent.mkdir(parents=True, exist_ok=True)
    # The exe writes the CSV itself so a partial file is not a previous run.
    if args.out.is_file():
        args.out.unlink()
    dotnet = shutil.which("dotnet", path=env.get("PATH"))
    assert dotnet is not None
    proc = subprocess.run(
        [
            dotnet,
            "exec",
            str(built),
            args.problem,
            str(partitions),
            str(pop),
            str(gens),
            str(args.seed),
            str(args.out.resolve()),
        ],
        check=False,
        capture_output=True,
        text=True,
        env=env,
    )
    sys.stderr.write(proc.stderr or "")
    if proc.returncode != 0 or not args.out.is_file():
        detail = (proc.stderr or proc.stdout or "catalog dump failed").strip()
        if len(detail) > 800:
            detail = detail[:800] + "…"
        return skip(f"C# catalog run failed: {detail}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
