#!/usr/bin/env python3
"""Dump a Bend Unsga3Algorithm.Run front.

Default: short ZDT1 smoke via src/run_smoke.bend (n=30, partitions=4,
pop=8, gens=3, seed=1, PymooCompatible). Labeled smoke — not the C#
OracleCompare protocol.

With --problem/--partitions/--pop/--gens/--seed, generate a small Bend
wrapper and run that (oracle-sized runs are opt-in and can be slow).

Writes CSV under ab/out/. Does not invent IGD / HV numbers.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_BEND = ROOT / "src" / "run_smoke.bend"
OUT_DIR = ROOT / "ab" / "out"

PROBLEMS = {
    "zdt1": ("Prob.zdt1(30n)", 2),
    "zdt2": ("Prob.zdt2(30n)", 2),
    "dtlz2": ("Prob.dtlz2(3n, 10n)", 3),
}


def generate_bend(problem: str, partitions: int, pop: int, gens: int, seed: int) -> str:
    ctor, n_obj = PROBLEMS[problem]
    return f"""# Generated by ab/dump_bend_run.py — do not edit.
import Base
import ../../src/algorithm.bend as Algo
import ../../src/problems.bend as Prob
import ../../src/reference_directions.bend as Refs
import ../../src/tournament.bend as Tour

def main() -> IO(Unit):
  do IO<Unit>:
    IO.print("# run: {problem} n_obj={n_obj} partitions={partitions} pop={pop} gens={gens} seed={seed} tournament=PymooCompatible")
    Algo.emit_front(Algo.nd_front(Algo.run({ctor}, Algo.mk(Refs.das_dennis({n_obj}n, {partitions}n), {pop}n, {gens}n, {seed}n, Tour.pymoo(), True{{}}))))
"""


def run_bend(path: Path) -> str:
    proc = subprocess.run(
        ["bend", str(path)],
        check=False,
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        sys.stderr.write(proc.stderr or proc.stdout or "bend failed\n")
        raise SystemExit(proc.returncode)
    return proc.stdout


def write_csv(text: str, dest: Path) -> int:
    dest.parent.mkdir(parents=True, exist_ok=True)
    lines = [ln for ln in text.splitlines() if ln.strip()]
    dest.write_text("\n".join(lines) + ("\n" if lines else ""), encoding="utf-8")
    return len([ln for ln in lines if not ln.startswith("#")])


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--problem", choices=sorted(PROBLEMS), default=None)
    parser.add_argument("--partitions", type=int, default=None)
    parser.add_argument("--pop", type=int, default=None)
    parser.add_argument("--gens", type=int, default=None)
    parser.add_argument("--seed", type=int, default=None)
    parser.add_argument(
        "--out",
        type=Path,
        default=OUT_DIR / "bend_run_F.csv",
        help="CSV path for the ND front (default ab/out/bend_run_F.csv)",
    )
    args = parser.parse_args()

    custom = any(
        v is not None
        for v in (args.problem, args.partitions, args.pop, args.gens, args.seed)
    )
    if custom:
        problem = args.problem or "zdt1"
        partitions = args.partitions if args.partitions is not None else 12
        pop = args.pop if args.pop is not None else 52
        gens = args.gens if args.gens is not None else 100
        seed = args.seed if args.seed is not None else 1
        OUT_DIR.mkdir(parents=True, exist_ok=True)
        generated = OUT_DIR / "run_custom.bend"
        generated.write_text(
            generate_bend(problem, partitions, pop, gens, seed),
            encoding="utf-8",
        )
        print(
            f"generated {generated} ({problem} p={partitions} pop={pop} "
            f"gens={gens} seed={seed}) — not the checked-in smoke unless those "
            f"values match src/run_smoke.bend",
            file=sys.stderr,
        )
        stdout = run_bend(generated)
    else:
        src = DEFAULT_BEND
        print(f"running checked-in smoke {src}", file=sys.stderr)
        stdout = run_bend(src)

    n = write_csv(stdout, args.out)
    print(f"wrote {args.out} ({n} front rows)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
