#!/usr/bin/env python3
"""Dump a Bend Unsga3Algorithm.Run front.

Default: short ZDT1 smoke via src/run_smoke.bend (n=30, partitions=4,
pop=8, gens=3, seed=1, PymooCompatible). Labeled smoke — not the C#
OracleCompare protocol.

With --problem/--partitions/--pop/--gens/--seed, generate a small Bend
wrapper and run that (oracle-sized runs are opt-in and can be slow).

Native path (clang 14+; Bend 2.0.10+):
  bend <driver> -o ab/out/run_cache/<sha256(driver)>
  ./ab/out/run_cache/<sha256> --threads 8

`--native` skips `bend -o` when that cache path is already executable
(same driver source bytes). A miss compiles into the cache, then runs.
Stderr splits compile vs run (`compile_s`, `run_s`) so wall time is not
mistaken for Bend Run cost. If `bend … -o` fails, it prints the compiler
output and falls back to `bend file.bend` (interpreter/check-run).

`--bin` and `--interpreter` are unchanged. Does not invent IGD / HV.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_BEND = ROOT / "src" / "run_smoke.bend"
OUT_DIR = ROOT / "ab" / "out"
CUSTOM_BEND = OUT_DIR / "run_custom.bend"
CACHE_DIR = OUT_DIR / "run_cache"

PROBLEMS = {
    "zdt1": ("Prob.zdt1(30n)", 2),
    "zdt2": ("Prob.zdt2(30n)", 2),
    "dtlz2": ("Prob.dtlz2(3n, 10n)", 3),
}

CHECKER_PREFIXES = ("All terms check",)


def generate_bend(problem: str, partitions: int, pop: int, gens: int, seed: int) -> str:
    ctor, n_obj = PROBLEMS[problem]
    return f"""# Generated by ab/dump_bend_run.py — do not edit.
import Base
import ../../src/algorithm.bend as Algo
import ../../src/problems.bend as Prob
import ../../src/reference_directions.bend as Refs
import ../../src/tournament.bend as Tour

def main() -> IO(Unit):
  do IO<Unit>:
    IO.print("# run: {problem} n_obj={n_obj} partitions={partitions} pop={pop} gens={gens} seed={seed} tournament=PymooCompatible")
    Algo.emit_front(Algo.nd_front(Algo.run({ctor}, Algo.mk(Refs.das_dennis({n_obj}n, {partitions}n), {pop}n, {gens}n, {seed}n, Tour.pymoo(), True{{}}))))
"""


def extract_front_text(text: str) -> str:
    """Keep the # header + CSV rows; drop Bend checker banners."""
    lines: list[str] = []
    for ln in text.splitlines():
        s = ln.strip()
        if not s:
            continue
        if any(s.startswith(p) for p in CHECKER_PREFIXES):
            continue
        lines.append(s)
    return "\n".join(lines) + ("\n" if lines else "")


def run_cmd(cmd: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(cmd, check=False, capture_output=True, text=True)


def run_bend_interpret(path: Path) -> str:
    proc = run_cmd(["bend", str(path)])
    if proc.returncode != 0:
        sys.stderr.write(proc.stderr or proc.stdout or "bend failed\n")
        raise SystemExit(proc.returncode)
    return proc.stdout


def source_digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def cache_bin_for(src: Path) -> Path:
    return CACHE_DIR / source_digest(src)


def is_executable(path: Path) -> bool:
    return path.is_file() and os.access(path, os.X_OK)


def build_native(src: Path, dest: Path) -> tuple[bool, str]:
    dest.parent.mkdir(parents=True, exist_ok=True)
    proc = run_cmd(["bend", str(src), "-o", str(dest)])
    log = (proc.stderr or "") + (proc.stdout or "")
    ok = proc.returncode == 0 and is_executable(dest)
    return ok, log


def run_native(bin_path: Path, threads: int | None) -> str:
    cmd = [str(bin_path)]
    if threads is not None:
        cmd.extend(["--threads", str(threads)])
    proc = run_cmd(cmd)
    if proc.returncode != 0:
        sys.stderr.write(proc.stderr or proc.stdout or "native binary failed\n")
        raise SystemExit(proc.returncode)
    return proc.stdout


def write_csv(text: str, dest: Path) -> int:
    dest.parent.mkdir(parents=True, exist_ok=True)
    body = extract_front_text(text)
    dest.write_text(body, encoding="utf-8")
    return len([ln for ln in body.splitlines() if ln and not ln.startswith("#")])


def env_flag(name: str) -> bool:
    return os.environ.get(name, "").strip().lower() in ("1", "true", "yes", "on")


def fmt_secs(seconds: float) -> str:
    return f"{seconds:.3f}"


def want_native(args: argparse.Namespace, cached: Path | None) -> str:
    """Why we should try a native binary, or empty to interpret."""
    if args.interpreter:
        return ""
    if args.bin is not None:
        return "bin"
    if args.native or env_flag("UNSGA3_BEND_NATIVE"):
        return "native"
    if cached is not None and is_executable(cached):
        return "cached"
    return ""


def emit_compile_s(seconds: float) -> None:
    print(f"native: compile_s={fmt_secs(seconds)}", file=sys.stderr)


def emit_run_s(seconds: float) -> None:
    print(f"native: run_s={fmt_secs(seconds)}", file=sys.stderr)


def run_native_timed(bin_path: Path, threads: int | None) -> str:
    t0 = time.perf_counter()
    out = run_native(bin_path, threads)
    emit_run_s(time.perf_counter() - t0)
    return out


def emit_via(
    src: Path,
    dest_bin: Path,
    mode: str,
    threads: int | None,
    bin_override: Path | None,
) -> str:
    if mode == "bin":
        assert bin_override is not None
        print(f"native: using --bin {bin_override}", file=sys.stderr)
        return run_native_timed(bin_override, threads)

    if mode == "cached":
        print(f"native: cache hit {dest_bin}", file=sys.stderr)
        try:
            return run_native_timed(dest_bin, threads)
        except SystemExit:
            print(
                f"native: available binary failed; falling back to `bend {src}`",
                file=sys.stderr,
            )
            return run_bend_interpret(src)

    if mode == "native":
        if is_executable(dest_bin):
            print(f"native: cache hit {dest_bin}", file=sys.stderr)
            return run_native_timed(dest_bin, threads)

        print(f"native: building {src} -o {dest_bin}", file=sys.stderr)
        t0 = time.perf_counter()
        ok, log = build_native(src, dest_bin)
        emit_compile_s(time.perf_counter() - t0)
        if ok:
            return run_native_timed(dest_bin, threads)
        print(
            f"native: build failed; falling back to `bend {src}` "
            f"(interpreter/check-run)",
            file=sys.stderr,
        )
        if log.strip():
            sys.stderr.write(log)
            if not log.endswith("\n"):
                sys.stderr.write("\n")
        return run_bend_interpret(src)

    print(f"running `bend {src}` (interpreter/check-run)", file=sys.stderr)
    return run_bend_interpret(src)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--problem", choices=sorted(PROBLEMS), default=None)
    parser.add_argument("--partitions", type=int, default=None)
    parser.add_argument("--pop", type=int, default=None)
    parser.add_argument("--gens", type=int, default=None)
    parser.add_argument("--seed", type=int, default=None)
    parser.add_argument(
        "--out",
        type=Path,
        default=OUT_DIR / "bend_run_F.csv",
        help="CSV path for the ND front (default ab/out/bend_run_F.csv)",
    )
    parser.add_argument(
        "--native",
        action="store_true",
        help="build with `bend <driver> -o <cache-bin>` when the driver "
        "source hash misses, then run the binary (fallback to "
        "`bend <driver>` if the build fails)",
    )
    parser.add_argument(
        "--interpreter",
        action="store_true",
        help="force `bend <driver>` (skip native even if a binary is cached)",
    )
    parser.add_argument(
        "--bin",
        type=Path,
        default=None,
        help="run this already-built native binary instead of compiling",
    )
    parser.add_argument(
        "--threads",
        type=int,
        default=None,
        help="native binary --threads N (1–128). Default None omits the flag; "
        "Bend then uses cpu_count() (online CPUs ∩ affinity ∩ cgroup quota; "
        "binary --help: “default: the CPU count”). Not a Python nproc() inject.",
    )
    args = parser.parse_args()

    if args.native and args.interpreter:
        print("choose one of --native or --interpreter", file=sys.stderr)
        return 2
    if args.bin is not None and args.interpreter:
        print("choose one of --bin or --interpreter", file=sys.stderr)
        return 2
    if args.bin is not None and not args.bin.is_file():
        print(f"missing --bin: {args.bin}", file=sys.stderr)
        return 2

    custom = any(
        v is not None
        for v in (args.problem, args.partitions, args.pop, args.gens, args.seed)
    )
    if custom:
        problem = args.problem or "zdt1"
        partitions = args.partitions if args.partitions is not None else 12
        pop = args.pop if args.pop is not None else 52
        gens = args.gens if args.gens is not None else 100
        seed = args.seed if args.seed is not None else 1
        OUT_DIR.mkdir(parents=True, exist_ok=True)
        generated = CUSTOM_BEND
        generated.write_text(
            generate_bend(problem, partitions, pop, gens, seed),
            encoding="utf-8",
        )
        print(
            f"generated {generated} ({problem} p={partitions} pop={pop} "
            f"gens={gens} seed={seed}) — not the checked-in smoke unless those "
            f"values match src/run_smoke.bend",
            file=sys.stderr,
        )
        src = generated
    else:
        src = DEFAULT_BEND

    dest_bin = cache_bin_for(src)
    cached: Path | None = dest_bin

    mode = want_native(args, cached)
    if args.threads is not None and mode == "":
        print(
            "--threads applies only to a native binary; ignoring",
            file=sys.stderr,
        )
    stdout = emit_via(src, dest_bin, mode, args.threads, args.bin)

    n = write_csv(stdout, args.out)
    print(f"wrote {args.out} ({n} front rows)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
