#!/usr/bin/env python3
"""Dump a Bend v0 survival front from an objective-vector fixture.

Default: run src/ab_select.bend (same vectors as ab/fixtures/core_2obj.json).
With --fixture FILE, generate a short Bend program from the JSON and run that.
Writes CSV under ab/out/. Does not invent IGD / HV numbers.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_FIXTURE = ROOT / "ab" / "fixtures" / "core_2obj.json"
DEFAULT_BEND = ROOT / "src" / "ab_select.bend"
OUT_DIR = ROOT / "ab" / "out"


def f32_lit(x: object) -> str:
    s = str(x)
    return s if "." in s or "e" in s or "E" in s else f"{s}.0"


def vec_lit(row: list[object]) -> str:
    return "[" + ", ".join(f32_lit(v) for v in row) + "]"


def generate_bend(fixture: dict) -> str:
    objs = fixture["objectives"]
    n_obj = int(fixture["n_obj"])
    partitions = int(fixture["partitions"])
    target = int(fixture["target_size"])
    rows = "\n  <> ".join(f"Ind.from_objectives({vec_lit(row)})" for row in objs)
    return f"""# Generated by ab/dump_bend_front.py — do not edit.
import Base
import ../../src/individual.bend as Ind
import ../../src/ab_select.bend as Ab

def pop() -> List<&2, Ind.Individual>:
  {rows}
  <> Nil{{}}

def main() -> IO(Unit):
  do IO<Unit>:
    selected : List<&2, Ind.Individual> = Ab.run_select(pop(), {target}n, {n_obj}n, {partitions}n)
    Ab.emit(selected)
"""


def run_bend(path: Path) -> str:
    proc = subprocess.run(
        ["bend", str(path)],
        check=False,
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        sys.stderr.write(proc.stderr or proc.stdout or "bend failed\n")
        raise SystemExit(proc.returncode)
    return proc.stdout


def write_csv(text: str, dest: Path) -> int:
    dest.parent.mkdir(parents=True, exist_ok=True)
    lines = [ln for ln in text.splitlines() if ln.strip()]
    dest.write_text("\n".join(lines) + ("\n" if lines else ""), encoding="utf-8")
    return len(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--fixture",
        type=Path,
        default=None,
        help="JSON fixture (objectives + n_obj + partitions + target_size). "
        "Omitted: run the checked-in src/ab_select.bend smoke.",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=OUT_DIR / "bend_F.csv",
        help="CSV path for the selected front (default ab/out/bend_F.csv)",
    )
    args = parser.parse_args()

    if args.fixture is None:
        src = DEFAULT_BEND
        print(f"running checked-in driver {src}", file=sys.stderr)
        stdout = run_bend(src)
    else:
        fixture_path = args.fixture
        if not fixture_path.is_file():
            print(f"missing fixture: {fixture_path}", file=sys.stderr)
            return 2
        fixture = json.loads(fixture_path.read_text(encoding="utf-8"))
        OUT_DIR.mkdir(parents=True, exist_ok=True)
        generated = OUT_DIR / "select_run.bend"
        generated.write_text(generate_bend(fixture), encoding="utf-8")
        print(f"generated {generated} from {fixture_path}", file=sys.stderr)
        stdout = run_bend(generated)

    n = write_csv(stdout, args.out)
    print(f"wrote {args.out} ({n} rows)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
