#!/usr/bin/env python3
"""Warm-cache native phase profile of Unsga3Algorithm.Run.

Wraps the same public calls as src/algorithm.bend (same RNG / same front)
with IO.now() millisecond buckets. Bend 2.0.13 has no sampling profiler
(official README limitations); this is the wall-clock path.

Default: checked-in smoke (ab/profile_smoke.bend). With --problem / --pop /
--gens / … a generated driver calls ab/profile_run.bend.

Native only for run_s (compile reported separately). Warm cache:
  bend <driver> -o ab/out/profile_cache/<sha256(driver)>
  ./bin --threads N

Does not invent IGD / HV. Phase lines are `# phase NAME ms=… pct=…`.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import subprocess
import sys
import time
from pathlib import Path

from protocol import default_gens

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "ab" / "out"
CACHE_DIR = OUT_DIR / "profile_cache"
SMOKE_BEND = ROOT / "ab" / "profile_smoke.bend"
CUSTOM_BEND = OUT_DIR / "profile_custom.bend"

PROBLEMS = {
    "zdt1": ("Prob.zdt1(30n)", 2),
    "zdt2": ("Prob.zdt2(30n)", 2),
    "dtlz2": ("Prob.dtlz2(3n, 10n)", 3),
}

PHASE_RE = re.compile(r"^# phase (\S+) ms=(\d+)(?: pct=(\d+))?")
CHECKER_PREFIXES = ("All terms check",)


def generate_bend(problem: str, partitions: int, pop: int, gens: int, seed: int) -> str:
    ctor, n_obj = PROBLEMS[problem]
    return f"""# Generated by ab/profile_bend_run.py — do not edit.
import Base
import ../profile_run.bend as Prof
import ../../src/algorithm.bend as Algo
import ../../src/problems.bend as Prob
import ../../src/reference_directions.bend as Refs
import ../../src/tournament.bend as Tour

def main() -> IO(Unit):
  do IO<Unit>:
    Prof.run_and_emit(
      {ctor},
      Algo.mk(Refs.das_dennis({n_obj}n, {partitions}n), {pop}n, {gens}n, {seed}n, Tour.pymoo(), True{{}}),
      "{problem}",
      {n_obj}n,
      {partitions}n
    )
"""


def run_cmd(cmd: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(cmd, check=False, capture_output=True, text=True)


def source_digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def cache_bin_for(src: Path) -> Path:
    return CACHE_DIR / source_digest(src)


def is_executable(path: Path) -> bool:
    return path.is_file() and os.access(path, os.X_OK)


def fmt_secs(seconds: float) -> str:
    return f"{seconds:.3f}"


def build_native(src: Path, dest: Path) -> tuple[bool, str]:
    dest.parent.mkdir(parents=True, exist_ok=True)
    proc = run_cmd(["bend", str(src), "-o", str(dest)])
    log = (proc.stderr or "") + (proc.stdout or "")
    ok = proc.returncode == 0 and is_executable(dest)
    return ok, log


def run_native(bin_path: Path, threads: int | None) -> str:
    cmd = [str(bin_path)]
    if threads is not None:
        cmd.extend(["--threads", str(threads)])
    proc = run_cmd(cmd)
    if proc.returncode != 0:
        sys.stderr.write(proc.stderr or proc.stdout or "native binary failed\n")
        raise SystemExit(proc.returncode)
    return proc.stdout


def parse_phases(text: str) -> dict[str, tuple[int, int | None]]:
    out: dict[str, tuple[int, int | None]] = {}
    for ln in text.splitlines():
        m = PHASE_RE.match(ln.strip())
        if not m:
            continue
        name, ms, pct = m.group(1), int(m.group(2)), m.group(3)
        out[name] = (ms, int(pct) if pct is not None else None)
    return out


def parse_meta(text: str) -> dict[str, str]:
    meta: dict[str, str] = {}
    for ln in text.splitlines():
        s = ln.strip()
        if s.startswith("# profile:"):
            meta["header"] = s
            continue
        if s.startswith("# now_unit="):
            meta["now_unit"] = s.split("=", 1)[1]
            continue
        if s.startswith("# profile_sum_ms="):
            meta["sum_ms"] = s.split("=", 1)[1]
            continue
        if s.startswith("# profile_wall_ms="):
            meta["wall_ms"] = s.split("=", 1)[1]
    return meta


def print_table(phases: dict[str, tuple[int, int | None]], meta: dict[str, str]) -> None:
    if meta.get("header"):
        print(meta["header"], file=sys.stderr)
    unit = meta.get("now_unit", "ms")
    wall = meta.get("wall_ms", "?")
    total = meta.get("sum_ms", "?")
    print(f"# now_unit={unit} profile_sum_ms={total} profile_wall_ms={wall}", file=sys.stderr)
    print(f"{'phase':<24} {'ms':>10} {'s':>10} {'pct':>6}", file=sys.stderr)
    print("-" * 54, file=sys.stderr)
    order = [
        "init_pop",
        "evaluate",
        "nds_select",
        "nds_prepare",
        "nds_final",
        "nds",
        "normalize_select",
        "normalize_prepare",
        "normalize",
        "associate_select",
        "associate_prepare",
        "associate",
        "niche",
        "tournament",
        "offspring_sbx_pm_g12",
        "unaccounted",
    ]
    seen = set()
    for name in order:
        if name not in phases:
            continue
        seen.add(name)
        ms, pct = phases[name]
        pct_s = f"{pct}" if pct is not None else ""
        print(f"{name:<24} {ms:10d} {ms/1000:10.3f} {pct_s:>6}", file=sys.stderr)
    for name, (ms, pct) in phases.items():
        if name in seen:
            continue
        pct_s = f"{pct}" if pct is not None else ""
        print(f"{name:<24} {ms:10d} {ms/1000:10.3f} {pct_s:>6}", file=sys.stderr)


def extract_front_text(text: str) -> str:
    lines: list[str] = []
    for ln in text.splitlines():
        s = ln.strip()
        if not s:
            continue
        if any(s.startswith(p) for p in CHECKER_PREFIXES):
            continue
        if s.startswith("#"):
            continue
        lines.append(s)
    return "\n".join(lines) + ("\n" if lines else "")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--problem", choices=sorted(PROBLEMS), default=None)
    parser.add_argument("--partitions", type=int, default=None)
    parser.add_argument("--pop", type=int, default=None)
    parser.add_argument("--gens", type=int, default=None)
    parser.add_argument("--seed", type=int, default=1)
    parser.add_argument(
        "--out",
        type=Path,
        default=OUT_DIR / "profile_front.csv",
        help="optional ND-front CSV (header stripped)",
    )
    parser.add_argument(
        "--threads",
        type=int,
        default=None,
        help="pass --threads N to the native binary (Bend default: CPU count)",
    )
    parser.add_argument(
        "--rebuild",
        action="store_true",
        help="ignore a warm cache hit and run bend -o again (reports compile_s)",
    )
    args = parser.parse_args()

    custom = any(
        v is not None for v in (args.problem, args.partitions, args.pop, args.gens)
    )
    if custom:
        problem = args.problem or "zdt1"
        partitions = args.partitions if args.partitions is not None else 12
        pop = args.pop if args.pop is not None else 52
        gens = (
            args.gens
            if args.gens is not None
            else default_gens(problem, dtlz2_gens=100)
        )
        OUT_DIR.mkdir(parents=True, exist_ok=True)
        CUSTOM_BEND.write_text(
            generate_bend(problem, partitions, pop, gens, args.seed),
            encoding="utf-8",
        )
        src = CUSTOM_BEND
        print(
            f"generated {src} ({problem} p={partitions} pop={pop} "
            f"gens={gens} seed={args.seed})",
            file=sys.stderr,
        )
    else:
        src = SMOKE_BEND
        if not src.is_file():
            print(f"missing {src}", file=sys.stderr)
            return 2

    dest = cache_bin_for(src)
    compile_s: float | None = None
    if args.rebuild and dest.exists():
        dest.unlink()

    if is_executable(dest):
        print(f"native: cache hit {dest}", file=sys.stderr)
        print("native: compile_s=0.000 (warm; omitted)", file=sys.stderr)
    else:
        print(f"native: building {src} -o {dest}", file=sys.stderr)
        t0 = time.perf_counter()
        ok, log = build_native(src, dest)
        compile_s = time.perf_counter() - t0
        print(f"native: compile_s={fmt_secs(compile_s)}", file=sys.stderr)
        if not ok:
            sys.stderr.write(log)
            if log and not log.endswith("\n"):
                sys.stderr.write("\n")
            print("native: build failed", file=sys.stderr)
            return 1

    t0 = time.perf_counter()
    stdout = run_native(dest, args.threads)
    run_s = time.perf_counter() - t0
    print(f"native: run_s={fmt_secs(run_s)} (warm binary)", file=sys.stderr)

    phases = parse_phases(stdout)
    meta = parse_meta(stdout)
    print_table(phases, meta)

    body = extract_front_text(stdout)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(body, encoding="utf-8")
    n = len([ln for ln in body.splitlines() if ln])
    print(f"wrote {args.out} ({n} front rows)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
